# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start from a Node.js base image with the appropriate version
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install --ignore-scripts

# Copy the rest of the application source code
COPY src ./src
COPY tsconfig.json ./

# Build the application using TypeScript compiler
RUN npm run build

# Production image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy the built files from the builder image
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Set the environment variables required by the MCP server
ENV DESCOPE_PROJECT_ID=your-descope-project-id-here
ENV DESCOPE_MANAGEMENT_KEY=your-descope-management-key-here

# Define the command to run the MCP server
ENTRYPOINT ["node", "build/index.js"]